// Generated by CoffeeScript 1.8.0
var async, cleanCSS, exec, file_base, file_g, file_loader, file_md, fs, makeCSS, makeLoader, md, path, request;

fs = require('fs');

path = require('path');

exec = require('child_process').exec;

async = require('async');

request = require('superagent');

cleanCSS = require('clean-css');

md = 'https://raw.githubusercontent.com/sindresorhus/github-markdown-css/gh-pages/github-markdown.css';

file_md = './src/markdown.css';

file_base = './src/base.css';

file_g = './deploy/theme/g.css';

file_loader = './deploy/githublog.js';

makeCSS = function(cb) {
  return async.waterfall([
    function(next) {
      return request.get(md, function(res) {
        if (res.clientError || res.serverError || !res.text) {
          return next(res);
        }
        return next(null, res.text);
      });
    }, function(csstxt, next) {
      return fs.writeFile(file_md, csstxt, next);
    }, function(next) {
      return exec(['cat', file_base, file_md].join(' '), next);
    }, function(mergedcss, next) {
      return fs.writeFile(file_g, new cleanCSS().minify(mergedcss).styles, next);
    }
  ], cb);
};

makeCSS(function() {});

makeLoader = function() {
  return exec('cp -f ./lib/loader.js ' + file_loader, function() {
    return console.log('done');
  });
};

makeLoader(function() {});
