// Generated by CoffeeScript 1.8.0
var jade, jadeOpt, markdown;

markdown = require('markdown');

jade = require('jade');

jadeOpt = {
  cache: true,
  omitTag: 'radical',
  compileDebug: false
};

module.exports = function(theme) {
  var fn;
  fn = jade.compileFile(theme, jadeOpt);
  return function(article) {
    return fn(article);
  };
};
