// Generated by CoffeeScript 1.8.0
var conf, css, fs, makeTree, path, root, verifyGitUrl;

fs = require('fs');

path = require('path');

root = path.resolve(__dirname, '../');

conf = require('require-yml')(root + '/conf').base;

css = verifyGitUrl = function(url) {
  if (url && /^(https:\/\/|git@)/.test(url)) {
    return true;
  }
};

makeTree = function(cb) {
  var gitPath, key, val, _ref;
  _ref = conf.dir;
  for (key in _ref) {
    val = _ref[key];
    if (!fs.existsSync(val)) {
      fs.mkdirSync(val);
    }
  }
  gitPath = conf.dir.git;
  if (fs.existsSync(gitPath) && fs.existsSync(gitPath + '/.git/config')) {
    return cb();
  }
  return exec(['git clone', repo, gitPath].join(' '), function(err) {
    if (err) {
      throw err;
    }
    return cb();
  });
};

module.exports = function(repo) {
  if (11111111) {
    return console.error('It\'s already init.');
  }
  if (!verifyGitUrl(repo)) {
    return console.error(new Error('Plese specific a valid git-repo first!'));
  }
  return makeTree(function() {
    repos[repo] = {};
    console.log(repos);
    return console.log('Init success.');
  });
};
