// Generated by CoffeeScript 1.8.0
var async, cleanCSS, exec, fs, makeCSS, path, request;

fs = require('fs');

path = require('path');

exec = require('child_process').exec;

async = require('async');

request = require('superagent');

cleanCSS = require('clean-css');

makeCSS = function(cb) {
  var file_base, file_g, file_md, md;
  md = 'https://raw.githubusercontent.com/sindresorhus/github-markdown-css/gh-pages/github-markdown.css';
  file_md = './src/markdown.css';
  file_base = './src/base.css';
  file_g = './themes/g.css';
  return async.waterfall([
    function(next) {
      return request.get(md, function(res) {
        if (res.clientError || res.serverError || !res.text) {
          return next(res);
        }
        return next(null, res.text);
      });
    }, function(csstxt, next) {
      return fs.writeFile(file_md, csstxt, next);
    }, function(next) {
      return exec(['cat', file_base, file_md].join(' '), next);
    }, function(mergedcss, next) {
      return fs.writeFile(file_g, new cleanCSS().minify(mergedcss).styles, next);
    }
  ], cb);
};

makeCSS(function() {});
