// Generated by CoffeeScript 1.8.0
var cleanCSS, conf, githubMarkdownCSS;

githubMarkdownCSS = require('github-markdown-css');

console.log(githubMarkdownCSS);

conf = require('require-yml')('../conf').base;

cleanCSS = require('clean-css');

module.exports = {
  make_g: function(themeDir, cb) {}
};
